import { useState, type FormEvent } from "react";
import { ArrowRight, ArrowUpRight, Check, Minus, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Reveal } from "./Reveal";
import { SectionLabel } from "./SectionLabel";

const faqs = [
 ["What type of design services do you provide?","Beyond covers brand identity, social media, print, packaging, campaign creative, presentations and business design—built as one cohesive visual system."],
 ["How can I start a project?","Send an email, call, message on WhatsApp or complete the project brief below. A short initial conversation helps us recommend the right scope."],
 ["How long does a design project take?","Timing depends on scope. A focused identity moves faster than a full brand with packaging and print. You’ll receive a clear timeline before work begins."],
 ["Do you provide source files?","Yes. Final source files are organised and handed over in the formats needed for both digital and print use."],
 ["Do you work outside Rajkot?","Yes. Design projects are handled remotely for clients beyond Rajkot, while printing and delivery are planned around your location."],
];
export function TestimonialFaq(){const[open,setOpen]=useState(0);return <><section className="testimonial section-pad"><div className="shell"><SectionLabel index="06">The standard</SectionLabel><Reveal><blockquote>“The finished design should feel inevitable—clear in its idea, exact in its craft, and entirely your own.”</blockquote></Reveal><p>Dhaval Patel <span>Founder & Creative Lead</span></p></div></section><section className="faq section-pad"><div className="shell faq-grid"><div><p className="kicker">Common questions</p><h2>Before we<br/><em>begin.</em></h2></div><div>{faqs.map(([q,a],i)=><article key={q} className={open===i?"open":""}><button onClick={()=>setOpen(open===i?-1:i)} aria-expanded={open===i}><span>0{i+1}</span><b>{q}</b>{open===i?<Minus/>:<Plus/>}</button><div className="faq-answer"><p>{a}</p></div></article>)}</div></div></section></>}

export function Contact(){const[sent,setSent]=useState(false);const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const fd=new FormData(e.currentTarget);const subject=encodeURIComponent(`Project enquiry from ${fd.get("name")}`);const body=encodeURIComponent(Array.from(fd.entries()).map(([k,v])=>`${k}: ${v}`).join("\n"));window.location.href=`mailto:beyondgraphicsrjk@gmail.com?subject=${subject}&body=${body}`;setSent(true)};return <section id="contact" className="contact section-pad"><div className="shell"><SectionLabel index="07">Start something</SectionLabel><Reveal><h2>LET’S BUILD<br/>SOMETHING<br/><em>REMARKABLE.</em></h2></Reveal><div className="contact-grid"><div className="contact-direct"><p>Have an idea ready to move beyond the ordinary? Tell us where you want to go.</p><a href="mailto:beyondgraphicsrjk@gmail.com">beyondgraphicsrjk@gmail.com <ArrowUpRight/></a><a href="tel:+919904799105">+91 99047 99105 <ArrowUpRight/></a><span>Rajkot, Gujarat · Working worldwide</span></div><form onSubmit={submit}><div className="form-grid"><Field label="Name" name="name" required/><Field label="Email" name="email" type="email" required/><Field label="Phone / WhatsApp" name="phone"/><Field label="Company" name="company"/><label><span>Service</span><select name="service" defaultValue=""><option value="" disabled>Select a service</option><option>Brand identity</option><option>Packaging design</option><option>Print design</option><option>Campaign creative</option><option>Business design</option><option>Not sure yet</option></select></label><Field label="Budget range" name="budget"/></div><label className="details"><span>Project details</span><textarea name="project details" rows={3} required placeholder="A little about the project, ambition and timing…"/></label><div className="form-submit"><Button variant="gold" size="xl" type="submit">Send project enquiry <ArrowRight/></Button>{sent&&<p role="status"><Check/> Your email app is ready with the brief.</p>}</div></form></div></div></section>}
function Field({label,name,type="text",required=false}:{label:string;name:string;type?:string;required?:boolean}){return <label><span>{label}{required&&" *"}</span><input name={name} type={type} required={required}/></label>}

export function Footer(){return <footer><div className="shell footer-top"><div><a href="#home" className="footer-logo">BEYOND</a><p>Creative direction, branding and print for businesses ready to be remembered.</p></div><div><small>Navigate</small>{["Home","About","Services","Work","Process","Contact"].map(x=><a key={x} href={`#${x.toLowerCase()}`}>{x}</a>)}</div><div><small>Connect</small><a href="mailto:beyondgraphicsrjk@gmail.com">Email</a><a href="https://www.instagram.com/beyond_graphics._/" target="_blank" rel="noreferrer">Instagram</a><a href="tel:+919904799105">Phone</a></div></div><div className="shell footer-bottom"><span>© 2026 Beyond Graphics</span><span>Design · Branding · Printing</span><a href="#home">Back to top ↑</a></div><div className="footer-word" aria-hidden="true">BEYOND</div></footer>}
